### ISSUE TITLE
Feature: http headers as input

### ISSUE THREAD

**Issue by elnerd** [ffleming/timing_attack#7]
Some applications have authentication tokens in HTTP headers.
X-Token: aabbccddeeff...

It would be nice if one could use this tool against http-headers as well.

**Comment by ffleming** [comment]
Good idea!

**Comment by elnerd** [comment]
Thanks,

I have tested it, and it seem to work for me.
Unfortunately, it does not seem like the implementation I am testing is vulnerable.

Have you been able to use this tool against unsafe string comparison?
Such as: return user_token == system_token

**Comment by ffleming** [comment]
In the wild, no - if you're running Camelflage, you can pass a delta param to verify functionality, but the brute-forcing function is more of a toy/PoC than a reliable tool.  Standard enumeration works great since we're generally talking db access, network latency, etc. but insecure string comparison is generally gonna happen too quick to detect easily.  Of course, I haven't built header auth into Camelflage yet, but it works for url params and post bodies.

Using a forced delta of 10 microseconds (that is, sleep 10 microseconds after each comparison in an insecure string comparison), I was able to recover a byte of the key after about 2-3 hours against localhost.

This is definitely something that should be in the README!  I have a rough transcript of my Arsenal presentation that I should link, too, that talks more about the limitations of brute-force mode
